### ISSUE TITLE
Mining new project

### ISSUE THREAD

**Issue by M12Shehab** [danielcalencar/raszzprime#2]
Hello all

Firstly, thanks for your effort to deploy this useful tool.

I want to mine a new project that is not on the projects list in the table **_linkedissuessvn_**. How can I enable this tool to retrieve the bug reports from JIRA?

I have the endpoint JIAR API and the project repo, but the problem is to find the configuration to start it.

Thanks,
Shehab

**Comment by danielcalencar** [comment]
Hello,

Thanks for your interest in this project. To mine a new project that is not on the current linkedissuessvn table, you will have to populate the table yourself with the information regarding the new project.

Kind regards,
Daniel
