### ISSUE TITLE
java.lang.ClassNotFoundException: br.ufrn.raszz.miner.szz.RaSZZ

### ISSUE THREAD

**Issue by TaoZheng-code** [danielcalencar/raszzprime#4]
java -cp raszzprime/core-connector/build/classes:raszzprime/core-connector/libs/*:raszzprime/DiffJ/build/classes:raszzprime/DiffJ/libs/*:raszzprime/RefactoringMiner_Adapted/build/classes:raszzprime/RefactoringMiner_Adapted/libs/*:raszzprime/refdiff-core/build/classes:raszzprime/refdiff-core/libs/*:raszzprime/RA-SZZ/libs/*:raszzprime/RA-SZZ/build/classes br.ufrn.raszz.miner.szz.RaSZZ
error
java.lang.ClassNotFoundException: br.ufrn.raszz.miner.szz.RaSZZ
I can't find this class

**Comment by danielcalencar** [comment]
Did you build all project modules as described in the README file?

**Comment by TaoZheng-code** [comment]
Hello
Thank you for your reply. Does "build all project modules" refer to those steps of "ant"？
Also, the "ant" step in the README has a small problem with some file paths, which can be corrected.
And “java-cp...” In which path should the command be run？
Thanks,
TaoZheng

**Comment by danielcalencar** [comment]
Yes, you need to run those commands to build the modules (this is specified in the readme file)
The readme file also explain the assumed directory.
